version: '3'
services:
  web:
    build: ./server
    ports:
    - "3000:3000"
    volumes:
    - ./server:/usr/src/app
    depends_on:
    - python
  python:
    build: ./docker/python
    volumes:
    - ./code:/app  # Assumes user code will be saved in the ./code directory
